#!/bin/bash

printf "\n>> (1/2) Change working directory to '/var/www/ppl_ta'...\n\n"
cd /var/www/ppl_ta

printf "\n>> (2/2) Running all tests...\n\n"
echo "$ROOT_PASS" | sudo -S vendor/bin/phpunit

if [[ $? -ne 0 ]]
then
	printf "\n\n(!) Test(s) failed.\n\n"
	exit 1
else
	printf "\n\n(i) Test(s) passed.\n\n"
fi